[project]
name = "automated_etl_pipeline"
version = "0.1.0"
description = "automated_etl_pipeline using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.201.1,<1.0.0"
]

[project.scripts]
automated_etl_pipeline = "automated_etl_pipeline.main:run"
run_crew = "automated_etl_pipeline.main:run"
train = "automated_etl_pipeline.main:train"
replay = "automated_etl_pipeline.main:replay"
test = "automated_etl_pipeline.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
